git:
    depth: 1

matrix:
    include:
        - os: osx
          install:
              - ./.travis/install_osx.sh
          script:
              - cmake -GNinja -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/* && ninja -j $(nproc) -k 0
    allow_failures:
        - os: osx
dist: trusty
sudo: false
language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        packages:
            - cmake
            - ninja-build
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev

env:
    global:
        - CXXFLAGS="-Wall -Wextra -Werror=all"
script:
    - cmake -GNinja . && ninja -j $(nproc) -k 0

notifications:
    irc:
        on_success: change
        on_failure: change
        channels:
            - "chat.freenode.net#dwarftherapist"
        use_notice: true
