matrix:
    include:
        - os: osx
          before_install:
            - brew update && { brew outdated qt || brew upgrade qt }
    allow_failures:
        - os: osx
dist: trusty
sudo: false
language: cpp
compiler:
    - clang
    - gcc
env:
    global:
        - CXXFLAGS="-Wall -Wextra -Werror"
addons:
    apt:
        packages:
            - cmake
            - ninja-build
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev
script:
    - cmake -GNinja . && ninja
notifications:
    irc:
        on_success: change
        on_failure: change
        channels:
            - "chat.freenode.net#dwarftherapist"
        use_notice: true
