git:
    depth: 1

matrix:
    include:
        - os: osx
          install:
            - ./.travis/install_osx.sh
    allow_failures:
        - os: osx
dist: trusty
sudo: false
language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        packages:
            - cmake
            - ninja-build
            - qtbase5-dev
            - qtbase5-dev-tools
            - qtdeclarative5-dev

env:
    global:
        - CXXFLAGS="-Wall -Wextra -Werror"
script:
    - cmake -GNinja . && ninja

notifications:
    irc:
        on_success: change
        on_failure: change
        channels:
            - "chat.freenode.net#dwarftherapist"
        use_notice: true
